
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SesProvider from './providers/SessProvider'
import { Button, CssBaseline } from '@mui/material'
import ThemesProvider, { ColorModeContext, useColorMode } from './providers/ThemesProvider'
import ThemeButton from './components/ThemeButton'
import Header from './components/Header'
import SideMenu from './components/SideMenu/SideMenu'
import { useSession } from 'next-auth/react'
import UserProvider from './providers/UserProvider'
import Footer from './components/Footer'
import getCurrentUser from './lib/action/getCurrentUser'
import ToasterProvider from './providers/ToasterProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shipesa',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const User = await getCurrentUser()
  const role = User?.role == 'Admin' ? 'Admin' : 'User';
  
  return (
    <html lang="en">
      <body className={inter.className}>
         <ThemesProvider currentMode='light'>
          <ToasterProvider />
            <SesProvider>
              <CssBaseline />
              {User && <Header user={role} ColorModeContext={ColorModeContext}/>}
              <UserProvider user={User}>
                {children}
              </UserProvider>
            </SesProvider>
         </ThemesProvider>
      </body>
    </html>
  )
}
